IOC_TOP = /reg/g/pcds/epics/ioc/common/ads-ioc/R0.1.6
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = MR1K4
PROJECT_PATH := ../../MR1K4/MR1K4.tsproj
PLC = MR1K4_PLC

PYTMC_OPTS = 
PREFIX = PREFIX:

include $(IOC_TOP)/iocBoot/templates/Makefile.base
